(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["common/main"],{2573:
/*!**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************!*\
  !*** ./node_modules/_babel-loader@8.2.3@babel-loader/lib!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--12-1!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/style.js!C:/Users/Administrator/Desktop/单子/修改/weixin134医院挂号系统设计与实现+ssm（微信端有问题，暂时不卖）/ssmu38p1/src/main/webapp/front/components/uni-load-more/uni-load-more.vue?vue&type=script&lang=js& ***!
  \**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/
/*! no static exports found */
/*! all exports used */
/*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(e,t,n){"use strict";(function(e){Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var n=e.getSystemInfoSync().platform,o={name:"UniLoadMore",props:{status:{type:String,default:"more"},showIcon:{type:Boolean,default:!0},iconType:{type:String,default:"auto"},iconSize:{type:Number,default:24},color:{type:String,default:"#777777"},contentText:{type:Object,default:function(){return{contentdown:"上拉显示更多",contentrefresh:"正在加载...",contentnomore:"没有更多数据了"}}}},data:function(){return{webviewHide:!1,platform:n}},computed:{iconSnowWidth:function(){return console.log(2*(Math.floor(this.iconSize/24)||1)),2*(Math.floor(this.iconSize/24)||1)}},mounted:function(){},methods:{onClick:function(){this.$emit("clickLoadMore",{detail:{status:this.status}})}}};t.default=o}).call(this,n(/*! ./node_modules/_@dcloudio_uni-mp-weixin@2.0.1-alpha-34020211231004@@dcloudio/uni-mp-weixin/dist/index.js */"9b21")["default"])},"39be":
/*!************************************************************************************************************************************************************!*\
  !*** C:/Users/Administrator/Desktop/单子/修改/weixin134医院挂号系统设计与实现+ssm（微信端有问题，暂时不卖）/ssmu38p1/src/main/webapp/front/components/uni-load-more/uni-load-more.vue ***!
  \************************************************************************************************************************************************************/
/*! no static exports found */
/*! all exports used */
/*! ModuleConcatenation bailout: Module exports are unknown */function(e,t,n){"use strict";n.r(t);var o=n(/*! ./uni-load-more.vue?vue&type=template&id=9c9b1a48&scoped=true& */"868e"),r=n(/*! ./uni-load-more.vue?vue&type=script&lang=js& */"e183");for(var u in r)["default"].indexOf(u)<0&&function(e){n.d(t,e,(function(){return r[e]}))}(u);n(/*! ./uni-load-more.vue?vue&type=style&index=0&id=9c9b1a48&lang=scss&scoped=true& */"a0d3");var c,i=n(/*! ./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/runtime/componentNormalizer.js */"5140"),a=Object(i["a"])(r["default"],o["b"],o["c"],!1,null,"9c9b1a48",null,!1,o["a"],c);t["default"]=a.exports},"6c71":
/*!**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************!*\
  !*** ./node_modules/_mini-css-extract-plugin@0.9.0@mini-css-extract-plugin/dist/loader.js??ref--8-oneOf-1-0!./node_modules/_css-loader@3.6.0@css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--8-oneOf-1-2!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??ref--8-oneOf-1-3!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/sass-loader/dist/cjs.js??ref--8-oneOf-1-4!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--8-oneOf-1-5!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/style.js!C:/Users/Administrator/Desktop/单子/修改/weixin134医院挂号系统设计与实现+ssm（微信端有问题，暂时不卖）/ssmu38p1/src/main/webapp/front/components/uni-load-more/uni-load-more.vue?vue&type=style&index=0&id=9c9b1a48&lang=scss&scoped=true& ***!
  \**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/
/*! no static exports found */
/*! exports used: default */
/*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(e,t,n){},8350:
/*!***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************!*\
  !*** ./node_modules/_mini-css-extract-plugin@0.9.0@mini-css-extract-plugin/dist/loader.js??ref--8-oneOf-1-0!./node_modules/_css-loader@3.6.0@css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--8-oneOf-1-2!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??ref--8-oneOf-1-3!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/sass-loader/dist/cjs.js??ref--8-oneOf-1-4!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--8-oneOf-1-5!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/style.js!C:/Users/Administrator/Desktop/单子/修改/weixin134医院挂号系统设计与实现+ssm（微信端有问题，暂时不卖）/ssmu38p1/src/main/webapp/front/App.vue?vue&type=style&index=0&lang=scss& ***!
  \***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/
/*! no static exports found */
/*! exports used: default */
/*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(e,t,n){},"868e":
/*!*******************************************************************************************************************************************************************************************************************!*\
  !*** C:/Users/Administrator/Desktop/单子/修改/weixin134医院挂号系统设计与实现+ssm（微信端有问题，暂时不卖）/ssmu38p1/src/main/webapp/front/components/uni-load-more/uni-load-more.vue?vue&type=template&id=9c9b1a48&scoped=true& + 1 modules ***!
  \*******************************************************************************************************************************************************************************************************************/
/*! exports provided: render, staticRenderFns, recyclableRender, components */
/*! exports used: components, render, staticRenderFns */function(e,t,n){"use strict";var o;n.d(t,"b",(function(){return r})),n.d(t,"c",(function(){return u})),n.d(t,"a",(function(){return o}));var r=function(){var e=this,t=e.$createElement;e._self._c},u=[]},9094:
/*!*************************************************************************************************************************!*\
  !*** C:/Users/Administrator/Desktop/单子/修改/weixin134医院挂号系统设计与实现+ssm（微信端有问题，暂时不卖）/ssmu38p1/src/main/webapp/front/App.vue ***!
  \*************************************************************************************************************************/
/*! no static exports found */
/*! all exports used */
/*! ModuleConcatenation bailout: Module exports are unknown */function(e,t,n){"use strict";n.r(t);var o=n(/*! ./App.vue?vue&type=script&lang=js& */"c30b");for(var r in o)["default"].indexOf(r)<0&&function(e){n.d(t,e,(function(){return o[e]}))}(r);n(/*! ./App.vue?vue&type=style&index=0&lang=scss& */"d8fd");var u,c,i,a,f=n(/*! ./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/runtime/componentNormalizer.js */"5140"),l=Object(f["a"])(o["default"],u,c,!1,null,null,null,!1,i,a);t["default"]=l.exports},a0d3:
/*!**********************************************************************************************************************************************************************************************************************!*\
  !*** C:/Users/Administrator/Desktop/单子/修改/weixin134医院挂号系统设计与实现+ssm（微信端有问题，暂时不卖）/ssmu38p1/src/main/webapp/front/components/uni-load-more/uni-load-more.vue?vue&type=style&index=0&id=9c9b1a48&lang=scss&scoped=true& ***!
  \**********************************************************************************************************************************************************************************************************************/
/*! no static exports found */
/*! ModuleConcatenation bailout: Module exports are unknown */function(e,t,n){"use strict";var o=n(/*! -!./node_modules/_mini-css-extract-plugin@0.9.0@mini-css-extract-plugin/dist/loader.js??ref--8-oneOf-1-0!./node_modules/_css-loader@3.6.0@css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--8-oneOf-1-2!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??ref--8-oneOf-1-3!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/sass-loader/dist/cjs.js??ref--8-oneOf-1-4!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--8-oneOf-1-5!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/style.js!./uni-load-more.vue?vue&type=style&index=0&id=9c9b1a48&lang=scss&scoped=true& */"6c71"),r=n.n(o);r.a},c30b:
/*!**************************************************************************************************************************************************!*\
  !*** C:/Users/Administrator/Desktop/单子/修改/weixin134医院挂号系统设计与实现+ssm（微信端有问题，暂时不卖）/ssmu38p1/src/main/webapp/front/App.vue?vue&type=script&lang=js& ***!
  \**************************************************************************************************************************************************/
/*! no static exports found */
/*! all exports used */
/*! ModuleConcatenation bailout: Module exports are unknown */function(e,t,n){"use strict";n.r(t);var o=n(/*! -!./node_modules/_babel-loader@8.2.3@babel-loader/lib!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--12-1!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/style.js!./App.vue?vue&type=script&lang=js& */"e78d"),r=n.n(o);for(var u in o)["default"].indexOf(u)<0&&function(e){n.d(t,e,(function(){return o[e]}))}(u);t["default"]=r.a},d17a:
/*!*************************************************************************************************************************!*\
  !*** C:/Users/Administrator/Desktop/单子/修改/weixin134医院挂号系统设计与实现+ssm（微信端有问题，暂时不卖）/ssmu38p1/src/main/webapp/front/main.js ***!
  \*************************************************************************************************************************/
/*! no static exports found */
/*! all exports used */
/*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(e,t,n){"use strict";(function(e){n(/*! uni-pages */"36ec");var t=d(n(/*! vue */"8fa0")),o=d(n(/*! ./App */"9094")),r=d(n(/*! ./utils/utils.js */"97cd")),u=d(n(/*! ./api/index.js */"9865e")),c=d(n(/*! ./api/base.js */"fcfa")),i=l(n(/*! utils/validate.js */"1dd4")),a=n(/*! @/utils/system */"b90c");d(n(/*! ./components/uni-load-more/uni-load-more.vue */"39be"));function f(e){if("function"!==typeof WeakMap)return null;var t=new WeakMap,n=new WeakMap;return(f=function(e){return e?n:t})(e)}function l(e,t){if(!t&&e&&e.__esModule)return e;if(null===e||"object"!==typeof e&&"function"!==typeof e)return{default:e};var n=f(t);if(n&&n.has(e))return n.get(e);var o={},r=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var u in e)if("default"!==u&&Object.prototype.hasOwnProperty.call(e,u)){var c=r?Object.getOwnPropertyDescriptor(e,u):null;c&&(c.get||c.set)?Object.defineProperty(o,u,c):o[u]=e[u]}return o.default=e,n&&n.set(e,o),o}function d(e){return e&&e.__esModule?e:{default:e}}function p(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);t&&(o=o.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,o)}return n}function s(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?p(Object(n),!0).forEach((function(t){b(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):p(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function b(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}wx.__webpack_require_UNI_MP_PLUGIN__=n;var v=function(){n.e(/*! require.ensure | components/uni-popup/uni-popup */"components/uni-popup/uni-popup").then(function(){return resolve(n(/*! ./components/uni-popup/uni-popup.vue */"d606"))}.bind(null,n)).catch(n.oe)},y=function(){Promise.all(/*! require.ensure | components/mescroll-uni/mescroll-uni */[n.e("common/vendor"),n.e("components/mescroll-uni/mescroll-uni")]).then(function(){return resolve(n(/*! ./components/mescroll-uni/mescroll-uni.vue */"7f8a"))}.bind(null,n)).catch(n.oe)};t.default.prototype.$utils=r.default,t.default.prototype.$base=c.default,t.default.prototype.$api=u.default,t.default.prototype.$validate=i,t.default.prototype.isAuth=a.isAuth,t.default.component("uniLoadMore",y),t.default.component("mescroll-uni",y),t.default.component("uni-popup",v),t.default.config.productionTip=!1,o.default.mpType="app";var m=new t.default(s({},o.default));e(m).$mount()}).call(this,n(/*! ./node_modules/_@dcloudio_uni-mp-weixin@2.0.1-alpha-34020211231004@@dcloudio/uni-mp-weixin/dist/index.js */"9b21")["createApp"])},d8fd:
/*!***********************************************************************************************************************************************************!*\
  !*** C:/Users/Administrator/Desktop/单子/修改/weixin134医院挂号系统设计与实现+ssm（微信端有问题，暂时不卖）/ssmu38p1/src/main/webapp/front/App.vue?vue&type=style&index=0&lang=scss& ***!
  \***********************************************************************************************************************************************************/
/*! no static exports found */
/*! ModuleConcatenation bailout: Module exports are unknown */function(e,t,n){"use strict";var o=n(/*! -!./node_modules/_mini-css-extract-plugin@0.9.0@mini-css-extract-plugin/dist/loader.js??ref--8-oneOf-1-0!./node_modules/_css-loader@3.6.0@css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--8-oneOf-1-2!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??ref--8-oneOf-1-3!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/sass-loader/dist/cjs.js??ref--8-oneOf-1-4!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--8-oneOf-1-5!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/style.js!./App.vue?vue&type=style&index=0&lang=scss& */"8350"),r=n.n(o);r.a},e183:
/*!*************************************************************************************************************************************************************************************!*\
  !*** C:/Users/Administrator/Desktop/单子/修改/weixin134医院挂号系统设计与实现+ssm（微信端有问题，暂时不卖）/ssmu38p1/src/main/webapp/front/components/uni-load-more/uni-load-more.vue?vue&type=script&lang=js& ***!
  \*************************************************************************************************************************************************************************************/
/*! no static exports found */
/*! all exports used */
/*! ModuleConcatenation bailout: Module exports are unknown */function(e,t,n){"use strict";n.r(t);var o=n(/*! -!./node_modules/_babel-loader@8.2.3@babel-loader/lib!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--12-1!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/style.js!./uni-load-more.vue?vue&type=script&lang=js& */"2573"),r=n.n(o);for(var u in o)["default"].indexOf(u)<0&&function(e){n.d(t,e,(function(){return o[e]}))}(u);t["default"]=r.a},e78d:
/*!***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************!*\
  !*** ./node_modules/_babel-loader@8.2.3@babel-loader/lib!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--12-1!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-alpha-34020211231004@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/_@dcloudio_webpack-uni-mp-loader@2.0.1-alpha-34020211231004@@dcloudio/webpack-uni-mp-loader/lib/style.js!C:/Users/Administrator/Desktop/单子/修改/weixin134医院挂号系统设计与实现+ssm（微信端有问题，暂时不卖）/ssmu38p1/src/main/webapp/front/App.vue?vue&type=script&lang=js& ***!
  \***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/
/*! no static exports found */
/*! all exports used */
/*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(e,t,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var o={onLaunch:function(){console.log("App Launch")},onShow:function(){console.log("App Show")},onHide:function(){console.log("App Hide")}};t.default=o}},[["d17a","common/runtime","common/vendor"]]]);